USE [master]
GO

/****** Object:  Database [scouting_7127]    Script Date: 3/18/2024 10:45:28 AM ******/
CREATE DATABASE [scouting_7127]
 CONTAINMENT = NONE
 --ON  PRIMARY 
--( NAME = N'scouting_7127', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.GOLD\MSSQL\DATA\scouting_7127.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 --LOG ON 
--( NAME = N'scouting_7127_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.GOLD\MSSQL\DATA\scouting_7127_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 --WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [scouting_7127].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [scouting_7127] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [scouting_7127] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [scouting_7127] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [scouting_7127] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [scouting_7127] SET ARITHABORT OFF 
GO

ALTER DATABASE [scouting_7127] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [scouting_7127] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [scouting_7127] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [scouting_7127] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [scouting_7127] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [scouting_7127] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [scouting_7127] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [scouting_7127] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [scouting_7127] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [scouting_7127] SET  DISABLE_BROKER 
GO

ALTER DATABASE [scouting_7127] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [scouting_7127] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [scouting_7127] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [scouting_7127] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [scouting_7127] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [scouting_7127] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [scouting_7127] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [scouting_7127] SET RECOVERY FULL 
GO

ALTER DATABASE [scouting_7127] SET  MULTI_USER 
GO

ALTER DATABASE [scouting_7127] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [scouting_7127] SET DB_CHAINING OFF 
GO

ALTER DATABASE [scouting_7127] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [scouting_7127] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [scouting_7127] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [scouting_7127] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [scouting_7127] SET QUERY_STORE = ON
GO

ALTER DATABASE [scouting_7127] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [scouting_7127] SET  READ_WRITE 
GO


